api_platform:
  title: "Symreact"
  description: "A simple API for distributing content"
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  doctrine:
    enabled: true
  collection:
    pagination:
      enabled: false
      items_per_page: 5
      client_enabled: true
      client_items_per_page: true
